[build]
  publish = "client/public"
  command = "npm install && npm run build:client"

[context.production.environment]
  VITE_SERVER_URL = "https://freechat-o1cb.onrender.com/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
