services:
  - name: backend
    type: web
    env: node
    buildCommand: npm install && npm run build:client && npm run build:server
    startCommand: npm run start
    rootDir: server
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false